/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock_management;

import Beans.bill_detail_bean;
import Beans.field_get_bean;
import Beans.fullstock_db_bean;
import Beans.stock_db_bean;
import Beans.stock_delete_bean;
import Beans.stock_update_bean;
//import Beans.product_update_bean;
import Beans.user_login_info;
import DAO.gst_get_dao;
//import Beans.no_of_quantity_bill;
//import DAO.field_get_dao;
import DAO.quantiy_get_dao;
import DAO.stock_delete_dao;
import DAO.stock_quantity_dao;
//import DAO.stock_table_dao;
import DAO.stock_update_dao;
import DB.db_connection;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author pathm
 */
public  class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
   public String b_no="";
  // public int billno=Integer.parseInt("1234");
    
    DefaultTableModel tb_add;
    
    user_login_info a=new user_login_info();
   //stock_update_dao dao=stock_update_dao();
    private Object quantiy_spiner;
    public String p_name,p_model,p_sno, p_prize, p_quantity, p_field, p_update,p_hsnno,product_name,Model_s,Quantity_s;
    public main() {
        initComponents();
          String col_add[]={"Product_name","Model","Price","GST","Quantity","total_price"};
         tb_add=new DefaultTableModel(col_add,0);
         add_to_card_tb.setModel(tb_add);
         
      
       //shows();
       jtab4.setVisible(false);
        jPanel3.setVisible(false);
       
    }
    
    
public void shows(){
    
   // login_bean a=new login_bean();
    String inf;
     inf=a.getUsername();
    System.out.println(inf+" info in shows");
   // head_lb.setText("WELCOME "+inf);
    
    
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        stock_update_btn = new javax.swing.JButton();
        stock_update_btn1 = new javax.swing.JButton();
        stock_update_btn2 = new javax.swing.JButton();
        jtab4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        show_quantity_table = new javax.swing.JTable();
        jPanel_update = new javax.swing.JPanel();
        field_items = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel_update_details = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        model_tf = new javax.swing.JTextField();
        serialno_tf = new javax.swing.JTextField();
        hsn_tf = new javax.swing.JTextField();
        prize_tf = new javax.swing.JTextField();
        product_name_tf = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        quantity_spinner = new javax.swing.JSpinner();
        update_form_lb = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_table = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        product_name_tf1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        combo_33 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        gst_tf = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        no_of_quantiy_available = new javax.swing.JTextField();
        prize_of_product = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        field_btn3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        total_amt_tf = new javax.swing.JTextField();
        total_amt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        add_to_card_tb = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        bill_no = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1965, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        stock_update_btn.setBackground(new java.awt.Color(153, 255, 153));
        stock_update_btn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        stock_update_btn.setText("STOCK UPDATE");
        stock_update_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 255, 153)));
        stock_update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_update_btnMouseClicked(evt);
            }
        });
        stock_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_update_btnActionPerformed(evt);
            }
        });

        stock_update_btn1.setBackground(new java.awt.Color(153, 255, 153));
        stock_update_btn1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        stock_update_btn1.setText("BILLING");
        stock_update_btn1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 255, 153)));
        stock_update_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_update_btn1MouseClicked(evt);
            }
        });
        stock_update_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_update_btn1ActionPerformed(evt);
            }
        });

        stock_update_btn2.setBackground(new java.awt.Color(153, 255, 153));
        stock_update_btn2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        stock_update_btn2.setText("NO OF STOCK");
        stock_update_btn2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 255, 153)));
        stock_update_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_update_btn2MouseClicked(evt);
            }
        });
        stock_update_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_update_btn2ActionPerformed(evt);
            }
        });

        show_quantity_table.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        show_quantity_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product name", "Model", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(show_quantity_table);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(3658, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtab4.addTab("no of stock", jPanel4);

        jPanel_update.setBackground(new java.awt.Color(255, 255, 204));

        field_items.setBackground(new java.awt.Color(255, 255, 204));
        field_items.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        field_items.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LAPTOP", "DESKTOP", "PRINTER", "MOBILE", "OTHERS" }));
        field_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_itemsActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton3.setText("SUBMIT");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel_update_details.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel9.setText("SERIAL NO");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel10.setText("GST ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel11.setText("PRODUCT NAME");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel12.setText("NO OF QUANTITY");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel13.setText("MODEL");

        model_tf.setBackground(new java.awt.Color(204, 255, 204));
        model_tf.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        model_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));

        serialno_tf.setBackground(new java.awt.Color(204, 255, 204));
        serialno_tf.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        serialno_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));
        serialno_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialno_tfActionPerformed(evt);
            }
        });

        hsn_tf.setBackground(new java.awt.Color(204, 255, 204));
        hsn_tf.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        hsn_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));
        hsn_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsn_tfActionPerformed(evt);
            }
        });

        prize_tf.setBackground(new java.awt.Color(204, 255, 204));
        prize_tf.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        prize_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));

        product_name_tf.setBackground(new java.awt.Color(204, 255, 204));
        product_name_tf.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        product_name_tf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));
        product_name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_name_tfActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 255, 102));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.setBorder(null);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel14.setText("PRIZE");

        quantity_spinner.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        quantity_spinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        quantity_spinner.setToolTipText("");

        update_form_lb.setBackground(new java.awt.Color(255, 204, 204));
        update_form_lb.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        update_form_lb.setForeground(new java.awt.Color(102, 102, 102));

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton5.setText("RESET");
        jButton5.setBorder(null);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 255, 102));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton6.setText("DELETE");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 102)));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_update_detailsLayout = new javax.swing.GroupLayout(jPanel_update_details);
        jPanel_update_details.setLayout(jPanel_update_detailsLayout);
        jPanel_update_detailsLayout.setHorizontalGroup(
            jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                        .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_update_detailsLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                                        .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(serialno_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(model_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                                        .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(product_name_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prize_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hsn_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                                        .addComponent(update_form_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64))
                                    .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                        .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_update_detailsLayout.setVerticalGroup(
            jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                .addComponent(update_form_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(product_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_update_detailsLayout.createSequentialGroup()
                        .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(model_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(serialno_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10))
                    .addComponent(hsn_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prize_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(40, 40, 40)
                .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(quantity_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        show_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product name", "Model", "Serial no", "Hsn no", "Prize", "Field", "Updated by"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        show_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(show_table);
        if (show_table.getColumnModel().getColumnCount() > 0) {
            show_table.getColumnModel().getColumn(0).setResizable(false);
            show_table.getColumnModel().getColumn(1).setResizable(false);
            show_table.getColumnModel().getColumn(2).setResizable(false);
            show_table.getColumnModel().getColumn(3).setResizable(false);
            show_table.getColumnModel().getColumn(4).setResizable(false);
            show_table.getColumnModel().getColumn(5).setResizable(false);
            show_table.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel20.setText("ENTER THE FIELD");

        product_name_tf1.setBackground(new java.awt.Color(204, 255, 204));
        product_name_tf1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        product_name_tf1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));
        product_name_tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_name_tf1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_updateLayout = new javax.swing.GroupLayout(jPanel_update);
        jPanel_update.setLayout(jPanel_updateLayout);
        jPanel_updateLayout.setHorizontalGroup(
            jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_updateLayout.createSequentialGroup()
                .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_updateLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel_update_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_updateLayout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(field_items, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2925, Short.MAX_VALUE))
            .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_updateLayout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addComponent(jLabel20)
                    .addContainerGap(4255, Short.MAX_VALUE)))
            .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_updateLayout.createSequentialGroup()
                    .addGap(2246, 2246, 2246)
                    .addComponent(product_name_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(2246, Short.MAX_VALUE)))
        );
        jPanel_updateLayout.setVerticalGroup(
            jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_updateLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_updateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel_updateLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel_update_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_updateLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel20)
                    .addContainerGap(891, Short.MAX_VALUE)))
            .addGroup(jPanel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_updateLayout.createSequentialGroup()
                    .addGap(490, 490, 490)
                    .addComponent(product_name_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(444, Short.MAX_VALUE)))
        );

        jtab4.addTab("update", jPanel_update);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SUPPLIER NAME");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("CONTACT NUMBER 2");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("CONTACT NUMBER 1");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("CONTACT NUMBER 2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(4198, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(350, 350, 350)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(4199, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jLabel5)
                    .addContainerGap(4470, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(587, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(858, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(254, 254, 254)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(680, Short.MAX_VALUE)))
        );

        jtab4.addTab("supplier details", jPanel6);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(null);

        combo_33.setBackground(new java.awt.Color(204, 204, 255));
        combo_33.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        combo_33.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_33ItemStateChanged(evt);
            }
        });
        combo_33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_33ActionPerformed(evt);
            }
        });
        jPanel5.add(combo_33);
        combo_33.setBounds(585, 320, 150, 34);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("NO OF STOCK AVAILABLE");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(974, 70, 312, 28);

        gst_tf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gst_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gst_tfActionPerformed(evt);
            }
        });
        jPanel5.add(gst_tf);
        gst_tf.setBounds(1400, 420, 102, 34);

        jSpinner1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel5.add(jSpinner1);
        jSpinner1.setBounds(1397, 252, 75, 34);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("SELETE THE FIELD");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(217, 70, 312, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("GST OF THE PRODUCT");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(974, 419, 284, 28);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("SELETE THE PRODUCT NAME");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(100, 203, 350, 28);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setText("PRIZE OF THE PRODUCT");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(974, 169, 312, 28);

        no_of_quantiy_available.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        no_of_quantiy_available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_of_quantiy_availableActionPerformed(evt);
            }
        });
        jPanel5.add(no_of_quantiy_available);
        no_of_quantiy_available.setBounds(1397, 67, 102, 34);

        prize_of_product.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel5.add(prize_of_product);
        prize_of_product.setBounds(1397, 166, 102, 34);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("TOTAL AMOUNT");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(974, 490, 312, 28);

        jButton1.setBackground(new java.awt.Color(153, 102, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(980, 330, 270, 29);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-billing-80.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(1390, 610, 110, 100);

        field_btn3.setBackground(new java.awt.Color(102, 102, 102));
        field_btn3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        field_btn3.setText("CLICK");
        jPanel5.add(field_btn3);
        field_btn3.setBounds(775, 111, 105, 0);

        jComboBox2.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(586, 200, 145, 34);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setText("SELECT THE MODEL");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(210, 330, 246, 28);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setText("QUANTITY NEEDED");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(972, 238, 261, 28);

        jButton7.setBackground(new java.awt.Color(153, 102, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton7.setText("CLEAR");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(990, 630, 170, 29);

        total_amt_tf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        total_amt_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_amt_tfActionPerformed(evt);
            }
        });
        jPanel5.add(total_amt_tf);
        total_amt_tf.setBounds(1400, 490, 102, 34);

        total_amt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        total_amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_amtActionPerformed(evt);
            }
        });
        jPanel5.add(total_amt);
        total_amt.setBounds(1400, 330, 102, 34);

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LAPTOP", "MOBILE", "PRINTER", "DESKTOP", "OTHERS" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1);
        jComboBox1.setBounds(590, 80, 130, 34);

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-add-to-cart-80.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(1220, 610, 110, 100);

        add_to_card_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        add_to_card_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_to_card_tbMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(add_to_card_tb);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(180, 440, 560, 330);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("BILL NO :");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(1060, 10, 120, 40);

        bill_no.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel5.add(bill_no);
        bill_no.setBounds(1180, 10, 260, 40);

        jtab4.addTab("billing", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(stock_update_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                        .addComponent(stock_update_btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(stock_update_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(stock_update_btn)
                .addGap(44, 44, 44)
                .addComponent(stock_update_btn1)
                .addGap(46, 46, 46)
                .addComponent(stock_update_btn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jtab4)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stock_update_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_update_btn2ActionPerformed
        // TODO add your handling code here:
        // jtab4.setSelectedIndex(1);
     //   show_quantity_table.removeAllElements();
       // Default
        //  show_quantity_table.setRowCount(0);
        // DefaultTableModel t2=(DefaultTableModel)show_quantity_table.getModel();
        DefaultTableModel tb=(DefaultTableModel)show_quantity_table.getModel();
        tb.setRowCount(0);
        

        

            show_quantity_table.setVisible(true);
            show_quantity_table();

            

        // show_quantity_table();
        // show_quantity_table.setVisible(false);

    }//GEN-LAST:event_stock_update_btn2ActionPerformed

    private void stock_update_btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_update_btn2MouseClicked
        // TODO add your handling code here:
        jtab4.setSelectedIndex(0);
    }//GEN-LAST:event_stock_update_btn2MouseClicked

    private void stock_update_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_update_btn1ActionPerformed
        // TODO add your handling code here:
        //jTablePane_field.setVisible(true)
        //   jTab1.setVisible(true);
        //jPanel_update_field.setVisible(true);
        //jPanel_update_details.setVisible(false);
        //  jtab4.setSelectedIndex(0);
        //b_no="1234";
        bill_num();
        // bill_no.setText(b_no);
    }//GEN-LAST:event_stock_update_btn1ActionPerformed

    private void stock_update_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_update_btn1MouseClicked
        // TODO add your handling code here:
        jtab4.setSelectedIndex(2);
    }//GEN-LAST:event_stock_update_btn1MouseClicked

    private void stock_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_update_btnActionPerformed
         // TODO add your handling code here:
        //new stock_update().setVisible(true);
        //   jPanel4.setVisible(true);
        //jtab4.setSelectedIndex(1);
        jtab4.setVisible(true);

    }//GEN-LAST:event_stock_update_btnActionPerformed

    private void stock_update_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_update_btnMouseClicked
        // TODO add your handling code here:
        jtab4.setSelectedIndex(1);
        //jtab4.setSelectedIndex(1);
        
        jPanel_update_details.setVisible(false);
    }//GEN-LAST:event_stock_update_btnMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:\

        String p_name=jComboBox2.getSelectedItem().toString();
        String model=combo_33.getSelectedItem().toString();
        String prize=prize_of_product.getText().toString();
        String GST=gst_tf.getText().toString();
        String quantity=jSpinner1.getValue().toString();
        String total=total_amt_tf.getText().toString();

        billing();

        stock_remove();
        String tb_bill[]={p_name,model,prize,GST,quantity,total};
        tb_add.addRow(tb_bill);
        no_of_quantiy_available.setText("");
        prize_of_product.setText("");
        jSpinner1.setValue(1);
        total_amt.setText("");
        gst_tf.setText("");
        total_amt_tf.setText("");

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        //System.out.println("combo1");
        jComboBox2.removeAllItems();
        get_pname();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void total_amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_amtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_amtActionPerformed

    private void total_amt_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_amt_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_amt_tfActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        no_of_quantiy_available.setText("");
        prize_of_product.setText("");
        jSpinner1.setValue(1);
        total_amt.setText("");
        gst_tf.setText("");
        total_amt_tf.setText("");

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        // String field_1=(String) co.getSelectedItem();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        String field_1=(String) jComboBox2.getSelectedItem();
        // jComboBox2.removeAllItems();
        combo_33.removeAllItems();
        get_model();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //  billing();
        String b_num=bill_no.getText();
        int billno=Integer.parseInt(b_num);

        billno=billno+1;
        String bill_n=String.valueOf(billno);
        bill_generate();

      //  b_no=bill_n;
       // bill_no.setText(b_no);
        

        // b_no.setText(bill_n);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //  quantiy_get_dao ab=new quantiy_get_dao();
        //ab.get_detail();
        //  stock_db_bean g_bean=new stock_db_bean();

        bill_detail_bean b_d=new bill_detail_bean();
        gst_get_dao gst_get=new gst_get_dao();

        b_d.setField((String) jComboBox1.getSelectedItem());

        b_d.setName((String) jComboBox2.getSelectedItem());
        b_d.setModel((String) combo_33.getSelectedItem());
        b_d.setPrize(prize_of_product.getText());

        /*
        //b_d.getQuanity()

        // int c=(int) jSpinner1.getValue();

        //  b_d.setQuanity();
        // b_d.setQuanity((String) jSpinner1.getValue());
        gst_get.get_bill_gst();
        // b_d.setGst();

        */
        gst_get.get_bill_gst();
        String gst=b_d.getGst();
        int a=parseInt(prize_of_product.getText());
        int value = (Integer) jSpinner1.getValue();
        int b=a*value;
        int GST=parseInt(gst);
        int prize=parseInt(prize_of_product.getText());
        //int quantity=parseInt((String) jSpinner1.getValue());
        GST=((GST*prize)/100)*value;
        //String g_s_t=GST.toString();
        // System.out.println("GST IS:"+GST);

        //String s=parseString(b);
        //total_amt.setText(s);
        // System.out.println("the gst from button "+GST);
        String t_otal=String.valueOf(b);
        total_amt.setText(t_otal);
        gst_tf.setText(String.valueOf(GST));
        //
        String f_amt=total_amt.getText();

        int total_amt=(parseInt(f_amt))+(GST);
        System.out.println("the amt from button "+total_amt);

        total_amt_tf.setText(String.valueOf(total_amt));

        //  System.out.println(g_bean.getGst()+"is GST");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void no_of_quantiy_availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_of_quantiy_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_of_quantiy_availableActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        // prize_of_items();

    }//GEN-LAST:event_jSpinner1StateChanged

    private void gst_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gst_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gst_tfActionPerformed

    private void combo_33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_33ActionPerformed

    private void combo_33ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_33ItemStateChanged
        // TODO add your handling code here:

        String mm=(String) combo_33.getSelectedItem();
        //no_of_quantity_bill qdao=new no_of_quantity_bill();
        //  no_of_quantity_bill qbil=new no_of_quantity_bill();

        /*qbil.setFileld(field_1);

        qbil.setP_name(Pname);
        qbil.setModel(model);
        String quant=qbil.getQuantity();
        no_of_quantiy_available.setText(quant);
        */
        getquantity(mm);

    }//GEN-LAST:event_combo_33ItemStateChanged

    private void product_name_tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_name_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_name_tf1ActionPerformed

    private void show_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_tableMouseClicked
        // TODO add your handling code here:

                    get_table_content();
        jPanel_update_details.setVisible(true);
    }//GEN-LAST:event_show_tableMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        DefaultTableModel tb=(DefaultTableModel)show_table.getModel();
        tb.setRowCount(0);
        show_table();
        jPanel3.setVisible(true);
        // jPanel_update_details.setVisible(false);
        delete();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here
        product_name_tf.setText(null);
        model_tf.setText(null);

        prize_tf.setText(null);
        serialno_tf.setText(null);
        hsn_tf.setText(null);
        quantity_spinner.setValue(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        //product_update_bean been=new product_update_bean();
        //  product_update_bean bean=new product_update_bean();
        String productname,prize,sno,hsnno,model,field,inf,quan;
        productname=product_name_tf.getText();
        stock_quantity_dao st_quan=new stock_quantity_dao();
        stock_update_bean update=new stock_update_bean();
        stock_update_dao dao=new stock_update_dao();
        quantiy_get_dao q_dao=new quantiy_get_dao();

        field=(String) field_items.getSelectedItem();
        model=model_tf.getText();

        prize=prize_tf.getText();
        sno=serialno_tf.getText();
        hsnno=hsn_tf.getText();
        quan=quantity_spinner.getValue().toString();
        //System.out.println(quan+" the quantity in main page");
        stock_update_bean.setField(field);

        update.setModel(model);

        update.setProductname(productname);

        update.setSno(sno);
        update.setHsnno(hsnno);
        update.setPrize(prize);
        update.setQuantity(quan);
        q_dao.get_detail();

        st_quan.no_of_stock();

        dao.stock_db();
        q_dao.get_detail();

        //  show_panel.setVisible(true);
        show_table();

        //show_table.setModel(a.t);
        jPanel3.setVisible(true);

        jPanel_update_details.setVisible(false);

        // bean.setProduct_Name(productname);
        // product_update_bean.setModel(model);
        // product_update_bean.setSno(sno);

        //bean.setModel(model);
        //product_update_bean.setPrize(prize);
        // product_update_bean.setSno(sno);
        //product_update_bean.setHsnno(hsnno);
        // bean.setProduct_Name(productname);
        // product_update_bean.setQuantity(quan);

        JOptionPane.showMessageDialog(this,"UPDATE SUCESSFULLY");
        jPanel_update_details.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        /* product_name=product_name_tf.getText();
        prize=prize_tf.getText();
        sno=serialno_tf.getText();
        model=model_tf.getText();
        hsnno=hsn_tf.getText();

        bean.setProductName(product_name);
        bean.setPrize(prize);
        bean.setModel(model);
        bean.setSno(sno);
        bean.setHsnno(hsnno);

        System.out.println("sucess ");

        JOptionPane.showMessageDialog(this,"updated sucessfully");

        jPanel_update_details.setVisible(false);
        */
    }//GEN-LAST:event_jButton4MouseClicked

    private void product_name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_name_tfActionPerformed

    private void hsn_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsn_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsn_tfActionPerformed

    private void serialno_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialno_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialno_tfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String field;
        field=(String) field_items.getSelectedItem();
        update_form_lb.setText("FILL THE "+field+" DETAILS");

        jPanel_update_details.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void field_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_itemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_itemsActionPerformed

    private void add_to_card_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_to_card_tbMouseClicked
        // TODO add your handling code here:
        table_value_get();
    }//GEN-LAST:event_add_to_card_tbMouseClicked
  int count=1;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable add_to_card_tb;
    private javax.swing.JLabel bill_no;
    private javax.swing.JComboBox combo_33;
    private javax.swing.JButton field_btn3;
    private javax.swing.JComboBox field_items;
    private javax.swing.JTextField gst_tf;
    private javax.swing.JTextField hsn_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_update;
    private javax.swing.JPanel jPanel_update_details;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTabbedPane jtab4;
    private javax.swing.JTextField model_tf;
    private javax.swing.JTextField no_of_quantiy_available;
    private javax.swing.JTextField prize_of_product;
    private javax.swing.JTextField prize_tf;
    private javax.swing.JTextField product_name_tf;
    private javax.swing.JTextField product_name_tf1;
    private javax.swing.JSpinner quantity_spinner;
    private javax.swing.JTextField serialno_tf;
    private javax.swing.JTable show_quantity_table;
    private javax.swing.JTable show_table;
    private javax.swing.JButton stock_update_btn;
    private javax.swing.JButton stock_update_btn1;
    private javax.swing.JButton stock_update_btn2;
    private javax.swing.JTextField total_amt;
    private javax.swing.JTextField total_amt_tf;
    private javax.swing.JLabel update_form_lb;
    // End of variables declaration//GEN-END:variables

    private stock_update_dao stock_update_dao() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void show_table() {
        fullstock_db_bean s_bean=new fullstock_db_bean();
        //String p_name=rs.getString("product_name");
            
        
             
        
       
        try{
           
         //   ArrayList<String>
       Connection con =db_connection.getcon();
            String query="SELECT * FROM item_info";
        System.out.println(query);
       Statement stm=con.createStatement();
        ResultSet rs=stm.executeQuery(query);
       // System.out.println(query);
        
        while(rs.next()){
            
            p_name=rs.getString("product_name");
            p_model=rs.getString("model");
            p_sno=rs.getString("serial_no");
            p_hsnno=rs.getString("hsn_no");
            p_prize=rs.getString("prize");
            // p_quantity=rs.getString("quantity");
             p_field=rs.getString("field");
           p_update=rs.getString("updated_by");
            
            
            
           String data[]= {p_name,p_model,p_sno,p_hsnno,p_prize,p_field,p_update};
           DefaultTableModel t=(DefaultTableModel)show_table.getModel();
          // DefaultTableModel tab;
          //  tab = (DefaultTableModel)show_table.setModel();
           
           
            
        t.addRow(data);
        
        
        
        }
        con.close();
       // show_table.setModel(t);
       
      //  show_table.setModel(DbUtils.resultSetToTableModel());
        }
        catch(Exception e){
            System.out.println(e+"exception form table dao");
        }
        
        s_bean.setProductname(p_name);
        s_bean.setModel(p_model);
        s_bean.setField(p_field);
        s_bean.setHsnno(p_hsnno);
        s_bean.setPrize(p_prize);
        s_bean.setQuantity(p_quantity);
        s_bean.setSno(p_sno);
        
        
}
    public void get_table_content(){
            int row=show_table.getSelectedRow();
            stock_delete_bean s_d_bean=new stock_delete_bean();
            
        String sh=show_table.getModel().getValueAt(row,0).toString();
        
        try{
           
         //   ArrayList<String>
       Connection con =db_connection.getcon();
            String query="SELECT * FROM item_info WHERE product_name='"+sh+"'";
        System.out.println(query);
       Statement stm=con.createStatement();
        ResultSet rs=stm.executeQuery(query);
       // System.out.println(query);
        
        while(rs.next()){
             
            String t_name=rs.getString("product_name");
            String t_model=rs.getString("model");
            String t_sno=rs.getString("serial_no");
            String t_hsnno=rs.getString("hsn_no");
            String t_prize=rs.getString("prize");
        //   String t_quantity=rs.getString("quantity");
            String t_field=rs.getString("field");
            String t_update=rs.getString("updated_by");
            int quant;
         //  quant = Integer.valueOf(t_quantity);
            
            
            product_name_tf.setText(t_name);
            model_tf.setText(t_model);
            serialno_tf.setText(t_sno);
            hsn_tf.setText(t_hsnno);
            prize_tf.setText(t_prize);
            s_d_bean.setName(t_name);
            s_d_bean.setModel(t_model);
            s_d_bean.setPrize(t_prize);
            
           // quantity_spinner.setValue(quant);
            
            
        }
        
        
            
        }
        catch(Exception e){
                System.out.println(e +" this exception in get_table_content() method ");
                }
    }
    public void show_quantity_table() {
        fullstock_db_bean s_bean=new fullstock_db_bean();
        //String p_name=rs.getString("product_name");
        
            
        
             
        
       
        try{
           
         //   ArrayList<String>
       Connection con =db_connection.getcon();
            String query1="SELECT * FROM stock_count_info";
        System.out.println(query1);
       Statement stm=con.createStatement();
        ResultSet rs=stm.executeQuery(query1);
       // System.out.println(query);
        
        while(rs.next()){
            
            product_name=rs.getString("product_name");
            Model_s=rs.getString("model");
            Quantity_s=rs.getString("quantity");
            
            
            
            
           String data1[]= {product_name,Model_s,Quantity_s};
           DefaultTableModel t2=(DefaultTableModel)show_quantity_table.getModel();
          // DefaultTableModel tab;
          //  tab = (DefaultTableModel)show_table.setModel();
           
           
            
        t2.addRow(data1);
        
        
        
        }
        con.close();
       // show_table.setModel(t);
       
      //  show_table.setModel(DbUtils.resultSetToTableModel());
        }
        catch(Exception e){
            System.out.println(e+"exception form table dao");
        }
        
     
        
        
}
    public void delete(){
        stock_delete_bean d_bean=new stock_delete_bean();
        stock_delete_dao s_del=new stock_delete_dao();
        String model,prize,sno,hsnno,name;
        name=product_name_tf.getText();
         model=model_tf.getText();
        
        
       prize=prize_tf.getText();
        sno=serialno_tf.getText();
        hsnno=hsn_tf.getText();
        
        d_bean.setName(name);
        d_bean.setModel(model);
        d_bean.setSno(sno);
        d_bean.setHsnno(hsnno);
        d_bean.setPrize(prize);
        
        s_del.stock_delete();
        
        
      // quan=quantity_spinner.getValue().toString();
        
    }

    private void show_quantit_table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    
        public void get_pname(){
        
    //field_get_bean a=new field_get_bean();
    String field_d=(String) jComboBox1.getSelectedItem();
    String name_f,model_f;
    int i=0;
     //   System.out.println("get_pname()");
       
       
      try{
     //   ArrayList<String>
       Connection con =db_connection.getcon();
      
            String query="SELECT product_name FROM  item_info WHERE field='"+field_d+"'";
          //   String query1="SELECT product_name FROM  item_info WHERE field='"+field_d+"'";
        System.out.println(query +"this query from get_pname()");
       Statement stm=con.createStatement();
        ResultSet rs=stm.executeQuery(query);
         //System.out.println(query +"this query from quantity_get_dao");
       
       // System.out.println(query);
        
        while(rs.next()){
            
            name_f=rs.getString("product_name");
           jComboBox2.addItem(name_f);
            
           //model_f=rs.getString("model");
            i++;
            //pr_quantity=rs.getString("quantity");
            
    
}
       // System.out.println(name_f+" thisi is name from field_get+dao");
         
        con.close();
    }
    catch(Exception e){
        System.out.println(e+" this exception comes form quantiy_get_dao");
    
}
    
   // System.out.println("the name from quantity_get_dao is:"+pr_name);
   //  s_bean.setPr_name(pr_name);
   // s_bean.setPr_model(pr_model);
   // s_bean.setPr_quantity(pr_quantity);
  //  sd_bean.setQuantity_from_db(pr_quantity);
    
    
    
    }
        
        
         public void get_model(){
        
   // field_get_bean a=new field_get_bean();
    //String field_d=a.getField();
             
    String name_f=(String) jComboBox1.getSelectedItem(),model_f= (String) jComboBox2.getSelectedItem();
    int i=0;
        
       
       
      try{
     //   ArrayList<String>
       Connection con =db_connection.getcon();
      
            String query="SELECT * FROM item_info WHERE field='"+name_f+"' and product_name='"+model_f+"'";
       //System.out.println(query +"this query from quantity_get_dao");
       Statement stm=con.createStatement();
        ResultSet rs=stm.executeQuery(query);
       //  System.out.println(query +"this query from quantity_get_dao");
       
       // System.out.println(query);
        
        while(rs.next()){
            
            name_f=rs.getString("model");
           combo_33.addItem(name_f);
            
           //model_f=rs.getString("model");
           // i++;
            //pr_quantity=rs.getString("quantity");
            
    
}
       // System.out.println(name_f+" thisi is name from field_get+dao");
         
        con.close();
    }
    catch(Exception e){
        System.out.println(e+" this exception comes form quantiy_get_dao");
    
}
    
   // System.out.println("the name from quantity_get_dao is:"+pr_name);
   //  s_bean.setPr_name(pr_name);
   // s_bean.setPr_model(pr_model);
   // s_bean.setPr_quantity(pr_quantity);
  //  sd_bean.setQuantity_from_db(pr_quantity);
    
    
    
    }
         
         public void billing(){
             
             String p_name=jComboBox2.getSelectedItem().toString();
        String model=combo_33.getSelectedItem().toString();
        String prize=prize_of_product.getText().toString();
        String GST=gst_tf.getText().toString();
        String quantity=jSpinner1.getValue().toString();
        String total=total_amt_tf.getText().toString();
        String bill_num=bill_no.getText().toString();
        
        Connection Con;
        
        ResultSet rs;
        
        try{
            Con=db_connection.getcon();
            String query="INSERT INTO billing VALUES('"+p_name+"','"+model+"','"+prize+"','"+GST+"','"+quantity+"','"+total+"','"+bill_num+"',curdate())";
            
            System.out.println(query +" this query from billing function");
           PreparedStatement stm= Con.prepareStatement(query);
           stm.executeUpdate();
       //  stm.executeUpdate(query);
               System.out.println(query +" this query from billing function");
               Con.close();
            
            
            
            
        }
        catch(Exception e){
           System.out.println(e+"this is error from billing()"); 
        }
             
             
             
         }
         
         public void getquantity(String mm){
             
             String f=(String) jComboBox1.getSelectedItem();
        String n=(String) jComboBox2.getSelectedItem();
       // String m=(String) combo_33.getSelectedItem();
       // String mm=(String) combo_33.getSelectedItem();
        String quant_y = null;
        String prize_1=null;
           //System.out.println(field_1 +" this the field from main page");
          // System.out.println(Pname +" this the name from main page");
         //  System.out.println(model +" this the model from main page");
             Connection con;
             Statement stm;
             ResultSet rs;
            // String qunati_ty;
             
             try{
                 con=db_connection.getcon();
                // String query="SELECT quantity FROM stock_count_info WHERE product_name='"+n+"' AND model='"+m+"' AND field='"+f+"'";
                                  // String query="SELECT quantity FROM stock_count_info WHERE product_name='"+n+"' AND model='"+m+"' AND field='"+f+"'";
                 String query="SELECT stock_count_info.quantity,item_info.prize FROM stock_count_info,item_info WHERE stock_count_info.product_name='"+n+"' AND stock_count_info.model='"+mm+"' AND stock_count_info.field='"+f+"' AND item_info.product_name='"+n+"' AND item_info.model='"+mm+"' AND item_info.field='"+f+"';";
               //  System.out.println(query);
                 stm=con.createStatement();
                  rs=stm.executeQuery(query);
                //  System.out.println(query +"this is query from getquanity()");
                  
                  while(rs.next()){
                       quant_y=rs.getString("quantity");
                       prize_1=rs.getString("prize");
                     
                       
                  }
                  System.out.println("the quantity is:   "+quant_y);
                   no_of_quantiy_available.setText(quant_y);
                  prize_of_product.setText(prize_1);
                   con.close();
                  
                  
                 
                 
             }
             catch(Exception e){
                 System.out.println(e+" this is the exception from main getquantity() method");
             }
        
             
         }

         
         public void bill_num(){
             Connection con;
             Statement stm;
             ResultSet rs;
             String bill_number;
             
             try{
                 con=db_connection.getcon();
                 String query="SELECT MAX(bill_no) FROM billing;";
                 System.out.println(query +"this erro from bill num()");
                 stm=con.createStatement();
                 rs=stm.executeQuery(query);
                 System.out.println(query +"this erro from bill num()");
                 while(rs.next()){
                     bill_number=rs.getString("MAX(bill_no)");
                     System.out.println(bill_number +"this is bill no");
                     int billnums=Integer.parseInt(bill_number);
                     int num_b=billnums+1;
                     bill_no.setText(String.valueOf(num_b));
                     System.out.println(bill_number +"this is bill no");
                 }
                 con.close();
                 
                         
                 
             }
             catch(Exception e){
                 
             }
         }
         public void stock_remove(){
             Statement stm;
             Connection con;
             ResultSet rs;
             
             int current_stock=Integer.parseInt(no_of_quantiy_available.getText());
             int quantity=Integer.parseInt(jSpinner1.getValue().toString());
             int total_quantity=current_stock-quantity;
             String p_name=jComboBox2.getSelectedItem().toString();
        String model=combo_33.getSelectedItem().toString();
             try{
                 
                 con=db_connection.getcon();
                 String query="UPDATE stock_count_info SET quantity='"+total_quantity+"' WHERE product_name='"+p_name+"' AND model='"+model+"'";
                 System.out.println(query +" this query from stock_remove()");
                 stm=con.createStatement();
                 stm.executeUpdate(query);
                  System.out.println(query +" this query from stock_remove()");
                  con.close();
                 
             }
             catch(Exception e){
                 System.out.println(e+" this is the exception from stock_remove()");
             }
             
         }
         public void bill_generate(){
             
        db_connection db=new db_connection();
        Connection conn;
        String bill_number=bill_no.getText();
         try {

            conn = db.getcon();

            JasperDesign jd = JRXmlLoader.load("C:\\Users\\pathm\\OneDrive\\Documents\\NetBeansProjects\\stock_management\\src\\stock_management\\billReport_1.jrxml");
            String sql = "SELECT * FROM billing WHERE bill_no='"+bill_number+"'";
            //'"+bill_number+"'
          //          + "login.task AS login_task FROM login login where date(login.date) between '"+from+"'  and '"+to+"' ";
            System.out.println(sql+" this is query form biil_generate() ");
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
           JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
          JasperViewer.viewReport(jp, false);
          System.out.println(sql+" this is query form biil_generate() ");


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
           // e.printStackTrace();

        }
         }
         public void table_value_get(){
              int row_table=show_table.getSelectedRow();
           // stock_delete_bean s_d_bean=new stock_delete_bean();
            
      //  String tb_data =show_table.getModel().getValueAt(row,0).toString();
             
         }
         
    private String parseString(int b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
         
         
         
        
             
         
}
